openapi: 3.0.2
info:
  title: employeeEngagementPlatform
  version: 1.0.0
paths:
  /users:
    post:
      requestBody:
        description: req body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            examples:
              user:
                value:
                  email: bob@gmail.com
                  password: mike12345
        required: true
      tags:
        - Users
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                User created:
                  value:
                    status: success
                    token: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2ZhMmQxMmFjYTExMjJkNzFhN2M0MCIsImlhdCI6MTY2OTMwOTEzNywiZXhwIjoxNjY5NTY4MzM3fQ.K6ROPFEi9euTkzjXurhuhoSfYGxNEKOIaUh7ZaXh3bA
                    data:
                      user:
                        email: bob@gmail.com
                        active: true
                        _id: 637fa2d12aca1122d71a7c40
                        __v: 0
          description: User created
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                user already exists:
                  value:
                    error: User already exists
          description: User already exists
      summary: Sign up a new user
      description: User created
  /sessions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
              properties:
                name:
                  type: string
                password:
                  type: string
              example:
                email: mike@gmail.com
                password: mike12345
            examples:
              user:
                value:
                  email: bob@gmail.com
                  password: mike12345
        required: true
      tags:
        - Users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                User added signed in:
                  value:
                    status: success
                    token: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2ZhZDZhNTg2MzA2MGQzM2JjMjk4NyIsImlhdCI6MTY2OTMxMzk3MywiZXhwIjoxNjY5NTczMTczfQ.UlCfzSqy9iBFLi6AELBrelKMDPjKKCTRoOAOTtOvaW4
                    data:
                      user:
                        _id: 637fad6a5863060d33bc2987
                        email: bob@gmail.com
                        __v: 0
          description: 'OK, user logged in'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                provide email and password:
                  value:
                    error: Please provide email and password!
          description: Incorrect email or password
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                user does not exist:
                  value:
                    error: User does not exist!
          description: User does not exist
      summary: Sign in a user
  /hours:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hours'
        required: true
      tags:
        - Hours
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                hours added:
                  value:
                    status: 200
                    hour:
                      userId: 6366eec1385c79a791f80ee9
                      month: November
                      year: 2009
                      days:
                        - createdAt: '2022-11-24T18:53:27.475Z'
                          day: wednesday
                          hours: 9
                          _id: 637fbe59390ad5ac854b6958
                      _id: 637fbe59390ad5ac854b6957
                      __v: 0
          description: hours added
        '400':
          headers:
            post header:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                bad request post header:
                  value: "access-control-allow-origin: * \r\n connection: keep-alive \r\n content-length: 53 \r\n content-type: application/json; charset=utf-8 \r\n date: Thu,24 Nov 2022 18:58:58 GMT \r\n etag: W/\"35-q2fHAoP/SAtZA4gjE6q54BdESFc\" \r\n keep-alive: timeout=5 \r\n x-powered-by: Express "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                required fields are not filled:
                  value:
                    error: required fields are not filled or in invalid format
          description: >-
            if requests body does not contain required fields or required fields are invalid
            format
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                not autorized:
                  value:
                    error: You are not logged in! Please log in to get access.
          description: not authorized
      security:
        - cookieAuth: []
      summary: Create new hours
    get:
      tags:
        - Hours
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/hours'
              examples:
                hours example:
                  value:
                    status: success
                    results: 3
                    data:
                      hours:
                        - _id: 637f2db1959440147ff828db
                          userId: 6366eec1385c79a791f80ee9
                          month: November
                          year: 2009
                          days:
                            - createdAt: '2022-11-24T08:31:00.755Z'
                              day: wednesday
                              hours: 9
                              _id: 637f2db1959440147ff828dc
                          __v: 0
          description: list of the hours
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                not authorized:
                  value:
                    error: You are not logged in! Please log in to get access.
          description: not authorized
      security:
        - cookieAuth: []
      summary: Returns list of hours
  '/hours/{id}':
    patch:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: object
                month:
                  type: string
                year:
                  type: number
                days:
                  type: object
                day:
                  type: object
            example:
              _id: 636a228c62df96c5baaec969
              userId: 6367edbf8901c69da661f0b9
              month: March
              year: 2011
              days:
                createdAt: '2022-11-08T09:23:38.336Z'
                day: 25
                hours: 7
                _id: 636a228c62df96c5baaec96a
        required: true
      tags:
        - Hours
      parameters:
        - example: 636a228c62df96c5baaec96a
          name: id
          description: ID of the hour
          schema:
            type: string
          in: path
          required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                hours:
                  value:
                    _id: 636a228c62df96c5baaec969
                    userId: 6367edbf8901c69da661f0b9
                    month: March
                    year: 2011
                    days:
                      createdAt: '2022-11-08T09:23:38.336Z'
                      day: 25
                      hours: 7
                      _id: 636a228c62df96c5baaec96a
          description: patches hours by id
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                bad request:
                  value:
                    message: >-
                      requests body does not contain required fields or required fields
                      are invalid format
          description: >-
            if requests body does not contain required fields or required fields are invalid
            format
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                not athorized:
                  value:
                    error: You are not logged in! Please log in to get access.
          description: not autorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hours'
              examples:
                not found:
                  value:
                    error: No document with the given ID
          description: Document not found
      security:
        - cookieAuth: []
      summary: Update hours
components:
  schemas:
    hours:
      title: Root Type for employees
      description: ''
      type: object
      items:
        $ref: '#/components/schemas/hours'
      example:
        userId: 6366eec1385c79a791f80ee9
        month: November
        year: 2009
        days:
          day: wednesday
          hours: 9
    user:
      title: Root Type for user
      description: user object
      type: object
      properties:
        status:
          type: string
        token:
          type: string
        data:
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                active:
                  type: boolean
                _id:
                  type: string
                __v:
                  format: int32
                  type: integer
      example:
        status: success
        token: >-
          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2ZhMmQxMmFjYTExMjJkNzFhN2M0MCIsImlhdCI6MTY2OTMwOTEzNywiZXhwIjoxNjY5NTY4MzM3fQ.K6ROPFEi9euTkzjXurhuhoSfYGxNEKOIaUh7ZaXh3bA
        data:
          user:
            email: bob@gmail.com
            active: true
            _id: 637fa2d12aca1122d71a7c40
            __v: 0
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: jwt
      in: cookie
